# Generated by Django 3.1.4 on 2020-12-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_slug', models.SlugField(default='slug')),
                ('project_description', models.TextField()),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
