# Generated by Django 3.1.4 on 2020-12-09 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('project_slug', models.SlugField()),
                ('project_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=200)),
                ('issue_description', models.TextField()),
                ('reviewer_status', models.CharField(choices=[('P', 'Pending Review'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=3)),
                ('posted_to_GitLab', models.BooleanField(default=False)),
                ('linked_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonticket.project')),
                ('linked_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anonticket.useridentifier')),
            ],
        ),
    ]
