# Generated by Django 3.1.4 on 2020-12-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useridentifier',
            old_name='user_identifer',
            new_name='user_identifier',
        ),
    ]
