# Generated by Django 3.1.4 on 2020-12-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AnonUser',
        ),
    ]
