# Generated by Django 3.1.4 on 2020-12-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_slug',
        ),
    ]
