# Generated by Django 3.1.4 on 2020-12-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0002_remove_project_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
