# Generated by Django 3.1.5 on 2021-01-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0002_auto_20210127_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gitlab_group',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_name_with_namespace',
        ),
    ]
