# Generated by Django 3.1.4 on 2020-12-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0002_auto_20201208_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonuser',
            name='user_identifer',
            field=models.CharField(default='testuser', max_length=200),
            preserve_default=False,
        ),
    ]
