# Generated by Django 3.1.4 on 2020-12-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0002_auto_20201210_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_iid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
