# Generated by Django 3.1.4 on 2020-12-07 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0003_project_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=200)),
                ('issue_description', models.TextField()),
                ('issue_status', models.CharField(choices=[('P', 'Pending Review'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=3)),
                ('linked_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonticket.project')),
            ],
        ),
    ]
