# Generated by Django 3.1.5 on 2021-01-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0003_auto_20210129_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GitLabGroup',
        ),
    ]
