# Generated by Django 3.1.4 on 2020-12-08 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0004_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='issue_status',
            new_name='reviewer_status',
        ),
        migrations.AddField(
            model_name='issue',
            name='posted_to_GitLab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='linked_user',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to='anonticket.user'),
            preserve_default=False,
        ),
    ]
