# Generated by Django 3.1.4 on 2021-01-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0005_delete_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gl_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('gl_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
