# Generated by Django 3.1.4 on 2021-01-07 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0006_gl_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gl_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anonticket.gl_group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
