# Generated by Django 3.1.4 on 2021-01-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0007_auto_20210107_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='gl_group',
            new_name='project_gl_group',
        ),
        migrations.AddField(
            model_name='project',
            name='project_name_with_namespace',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
