# Generated by Django 3.1.4 on 2021-01-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0008_auto_20210107_1726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gl_Group',
            new_name='GLGroup',
        ),
    ]
