# Generated by Django 3.1.4 on 2021-01-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0009_auto_20210107_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_slug',
            new_name='slug',
        ),
    ]
