# Generated by Django 3.1.4 on 2021-01-07 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0011_auto_20210107_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name_with_namespace',
            new_name='name_with_namespace',
        ),
    ]
