# Generated by Django 3.1.4 on 2021-01-07 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0013_auto_20210107_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_url',
            new_name='url',
        ),
    ]
