# Generated by Django 3.1.4 on 2021-01-07 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0014_auto_20210107_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_gl_group',
            new_name='gl_group',
        ),
    ]
