# Generated by Django 3.1.4 on 2021-01-07 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0015_auto_20210107_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glgroup',
            old_name='gl_id',
            new_name='gitlab_id',
        ),
    ]
