# Generated by Django 3.1.4 on 2021-01-07 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0016_auto_20210107_2352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GLGroup',
            new_name='GitLabGroup',
        ),
    ]
