# Generated by Django 3.1.4 on 2021-01-07 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0017_auto_20210107_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='gl_group',
            new_name='gitlab_group',
        ),
    ]
