# Generated by Django 3.1.4 on 2021-01-07 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0018_auto_20210107_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='issue_iid',
            new_name='gitlab_iid',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='issue_title',
            new_name='title',
        ),
    ]
