# Generated by Django 3.1.4 on 2021-01-08 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0019_auto_20210107_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='linked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonticket.useridentifier'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('issue_id', models.IntegerField()),
                ('gitlab_id', models.IntegerField(blank=True, null=True)),
                ('reviewer_status', models.CharField(choices=[('P', 'Pending Review'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=3)),
                ('posted_to_GitLab', models.BooleanField(default=False)),
                ('linked_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonticket.project')),
                ('linked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonticket.useridentifier')),
            ],
        ),
    ]
