# Generated by Django 3.1.4 on 2021-01-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0020_auto_20210108_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='issue_id',
            new_name='issue_iid',
        ),
    ]
