# Generated by Django 3.1.5 on 2021-01-15 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0022_auto_20210115_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='issue_title',
            new_name='gitlab_issue_title',
        ),
    ]
