# Generated by Django 3.1.5 on 2021-01-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0023_auto_20210115_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='gitlab_issue_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
