# Generated by Django 3.1.5 on 2021-01-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0024_auto_20210115_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='gitlab_issue_title',
        ),
    ]
