# Generated by Django 3.1.5 on 2021-01-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0025_remove_note_gitlab_issue_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='gitlab_issue_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
