# Generated by Django 3.1.5 on 2021-01-18 18:44

import anonticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0027_gitlabaccountrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabaccountrequest',
            name='username',
            field=models.SlugField(help_text='Type your requested username here. Note that your \n        username MUST start with a letter or number, and that usernames\n        can only use letters (A-Z, a-z), numbers, underscores (_), and \n        hyphens(-).', max_length=64, unique=True, validators=[anonticket.models.check_if_user_in_gitlab]),
        ),
    ]
