# Generated by Django 3.1.5 on 2021-01-20 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0028_auto_20210118_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentifier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
