# Generated by Django 3.1.5 on 2021-01-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0030_auto_20210120_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabaccountrequest',
            name='mod_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='mod_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='mod_comment',
            field=models.TextField(blank=True),
        ),
    ]
