# Generated by Django 3.1.5 on 2021-01-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0032_auto_20210120_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabaccountrequest',
            name='mod_comment',
            field=models.TextField(blank=True, help_text='As a moderator, you can add a comment to this item. \n        Once saved, it will appear on the moderator landing page and can\n        be seen by all moderators, but it will not be seen by users. ', verbose_name='Moderator Comment'),
        ),
        migrations.AlterField(
            model_name='note',
            name='mod_comment',
            field=models.TextField(blank=True, help_text='As a moderator, you can add a comment to this item. \n        Once saved, it will appear on the moderator landing page and can\n        be seen by all moderators, but it will not be seen by users. ', verbose_name='Moderator Comment'),
        ),
    ]
