# Generated by Django 3.1.5 on 2021-01-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonticket', '0033_auto_20210120_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_name_with_namespace',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
